# Basic project information
[project]
name = "comp0035-tutorials"
version = "2025.0.1"

# Most students will use setuptools, though poetry is also an option
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

# Setuptools configuration see https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration
[tool.setuptools.packages.find]
where = ["src"] # Not strictly required as default 'src' is automatically recognised by setuptools

# Setuptools configuration for the data files see https://setuptools.pypa.io/en/stable/userguide/datafiles.html
[tool.setuptools.package-data]
tutorialpkg = ["*.csv", "*.xlsx"]  # include all csv and xlsx files in the tutorialpkg package